"""
Django settings for financeinsights project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from django.conf.global_settings import LOGIN_URL
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"
DEBUG = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure")
    #"django-insecure-b@i@-zer8#+30d=9dzh+tutv&r(ls3*h0v=p*t0-s%w&_%wwqs"

# hosts from env (fallback to local dev)
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app_core",
    "app_web",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Team collaboration middleware
    "app_core.middleware.OrganizationMiddleware",
    "app_core.middleware.ActivityLoggingMiddleware",
]

ROOT_URLCONF = "financeinsights.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Team collaboration context
                "app_core.context_processors.organization_context",
            ],
        },
    },
]

WSGI_APPLICATION = "financeinsights.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Database: use DATABASE_URL if provided; else fallback to SQLite
db_url = os.getenv("DATABASE_URL", "").strip()
if not db_url:
    db_url = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

DATABASES = {
    "default": dj_database_url.parse(db_url, conn_max_age=600),
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Temporarily use default storage for development to avoid caching issues
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Email Configuration
# For development, use console backend to print emails to terminal
# For production, configure SMTP settings via environment variables
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Default: print to console
)

# SMTP settings (for production)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@financeinsights.com')


# ========== AI PLAYBOOK CONFIGURATION ==========

# AI Playbook Feature Toggle
AI_PLAYBOOK_ENABLED = os.getenv("AI_PLAYBOOK_ENABLED", "True").lower() == "true"

# AI Provider Selection - Options: "openai", "gemini", "huggingface", "groq"
AI_PROVIDER = os.getenv("AI_PROVIDER", "openai")  # Using OpenAI - most reliable for financial content

# OpenAI API Configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")  # Set in .env file - NEVER commit API keys!
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")  # Cost-effective, fast model

# Google Gemini API Configuration (FREE with generous limits!)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")  # Set in .env file
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-1.5-flash-latest")  # Latest stable free model

# Hugging Face API Configuration (DEPRECATED - 410 Gone)
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY", "")  # Set in .env file
HUGGINGFACE_MODEL = os.getenv("HUGGINGFACE_MODEL", "google/flan-t5-large")  # Not available anymore

# Groq API Configuration (FREE and FAST - ACTIVE!)
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")  # Will be set below
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")  # Fast, free, excellent quality

# Common AI Settings
OPENAI_MAX_TOKENS = int(os.getenv("OPENAI_MAX_TOKENS", "1500"))
OPENAI_TEMPERATURE = float(os.getenv("OPENAI_TEMPERATURE", "0.7"))

# Playbook Evaluation Settings
PLAYBOOK_EVALUATION_RETENTION_DAYS = int(os.getenv("PLAYBOOK_EVALUATION_RETENTION_DAYS", "365"))
PLAYBOOK_MAX_CONVERSATIONS_PER_USER = int(os.getenv("PLAYBOOK_MAX_CONVERSATIONS_PER_USER", "50"))

# Feature Flags
PLAYBOOK_ENABLE_FORECASTING = os.getenv("PLAYBOOK_ENABLE_FORECASTING", "True").lower() == "true"
PLAYBOOK_ENABLE_CONVERSATIONS = os.getenv("PLAYBOOK_ENABLE_CONVERSATIONS", "True").lower() == "true"

