# Generated by Django 5.2.7 on 2025-10-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "pattern",
                    models.CharField(
                        help_text="Substring or regex to match in description.",
                        max_length=256,
                    ),
                ),
                ("is_regex", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=128)),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=256)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "priority"],
                        name="app_core_ru_user_id_cd82f8_idx",
                    ),
                    models.Index(
                        fields=["user_id", "pattern"],
                        name="app_core_ru_user_id_f3fe73_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=512)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inflow", "Inflow"), ("outflow", "Outflow")],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("account", models.CharField(blank=True, default="", max_length=128)),
                ("source", models.CharField(blank=True, default="csv", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "date"],
                        name="app_core_tr_user_id_883c2f_idx",
                    ),
                    models.Index(
                        fields=["user_id", "category"],
                        name="app_core_tr_user_id_a74c5b_idx",
                    ),
                ],
            },
        ),
    ]
