# Generated by Django 5.2.7 on 2025-10-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0002_create_initial_superuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="app_core_tr_user_id_eac03f_idx",
            old_name="app_core_tr_user_id_883c2f_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="app_core_tr_user_id_a1220e_idx",
            old_name="app_core_tr_user_id_a74c5b_idx",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
