# Generated by Django 5.2.7 on 2025-10-25 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_core",
            "0003_rename_app_core_tr_user_id_883c2f_idx_app_core_tr_user_id_eac03f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="app_core_tr_user_id_eac03f_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="app_core_tr_user_id_a1220e_idx",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "date"], name="app_core_tr_user_id_883c2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "category"], name="app_core_tr_user_id_a74c5b_idx"
            ),
        ),
    ]
