# Generated by Django 5.2.7 on 2025-10-25 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0004_remove_transaction_app_core_tr_user_id_eac03f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rule",
            name="app_core_ru_user_id_cd82f8_idx",
        ),
        migrations.RemoveIndex(
            model_name="rule",
            name="app_core_ru_user_id_f3fe73_idx",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="user_id",
        ),
        migrations.AddField(
            model_name="rule",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["user", "priority"], name="app_core_ru_user_id_cd82f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["user", "pattern"], name="app_core_ru_user_id_f3fe73_idx"
            ),
        ),
    ]
