# Generated by Django 5.2.7 on 2025-10-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0006_alter_rule_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
