# Generated by Django 5.2.7 on 2025-11-08 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0008_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budget",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Custom end date (required for custom period)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Custom start date (required for custom period)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                    ("yearly", "Yearly"),
                    ("custom", "Custom Date Range"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="app_core_bu_start_d_f515b2_idx"
            ),
        ),
    ]
