# Generated by Django - data migration for categories to labels

from django.db import migrations
from django.db.models import Count


def convert_categories_to_labels(apps, schema_editor):
    """
    Auto-convert existing categories to labels.
    For each user, create labels from their unique transaction categories.
    """
    Transaction = apps.get_model('app_core', 'Transaction')
    Budget = apps.get_model('app_core', 'Budget')
    Label = apps.get_model('app_core', 'Label')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        # Get unique categories from user's transactions
        categories = Transaction.objects.filter(
            user=user
        ).exclude(
            category=''
        ).values_list('category', flat=True).distinct()

        label_map = {}

        # Create labels from categories
        for category in categories:
            if category and category.strip():
                # Create label if it doesn't exist
                label, created = Label.objects.get_or_create(
                    user=user,
                    name=category.strip(),
                    defaults={'color': '#2563eb'}  # Default blue color
                )
                label_map[category] = label

        # Update transactions with labels
        for category, label in label_map.items():
            Transaction.objects.filter(
                user=user,
                category=category,
                label__isnull=True  # Only update if no label set
            ).update(label=label)

        # Update budgets
        for budget in Budget.objects.filter(user=user):
            # If budget has no name, use category as name
            if not budget.name or budget.name == 'Unnamed Budget':
                budget.name = budget.category or 'General Budget'
                budget.save()

            # Add label to budget if category exists
            if budget.category and budget.category in label_map:
                budget.labels.add(label_map[budget.category])


def reverse_migration(apps, schema_editor):
    """
    Reverse: Remove label assignments (keep labels and category fields)
    """
    Transaction = apps.get_model('app_core', 'Transaction')
    Budget = apps.get_model('app_core', 'Budget')

    # Clear label references (but keep Label objects and category field)
    Transaction.objects.all().update(label=None)
    Budget.objects.all().clear()  # Clear M2M relationships


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_label_transaction_label_budget_name_budget_labels_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_categories_to_labels, reverse_migration),
    ]

