# Generated by Django 5.2.7 on 2025-11-13 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0011_convert_categories_to_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Transaction description", max_length=512
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Transaction amount", max_digits=12
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inflow", "Inflow"), ("outflow", "Outflow")],
                        help_text="Inflow or Outflow",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("account", models.CharField(blank=True, default="", max_length=128)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(help_text="Date of first occurrence")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional end date (leave blank for indefinite)",
                        null=True,
                    ),
                ),
                (
                    "last_generated_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date a transaction was generated",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to continue generating transactions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.RemoveIndex(
            model_name="budget",
            name="app_core_bu_user_id_5afc12_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="app_core_tr_user_id_a74c5b_idx",
        ),
        migrations.RenameIndex(
            model_name="label",
            new_name="app_core_la_user_id_d421be_idx",
            old_name="app_core_la_user_id_d8c442_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="app_core_tr_user_id_c5a750_idx",
            old_name="app_core_tr_user_lb_idx",
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DEPRECATED: Use labels instead",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(
                help_text="Budget name (e.g., 'Q4 Marketing', 'Office Renovation')",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DEPRECATED: Use label instead",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_transactions",
                to="app_core.label",
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(
                fields=["user", "active"], name="app_core_re_user_id_a36e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(
                fields=["start_date", "end_date"], name="app_core_re_start_d_caf6b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(
                fields=["last_generated_date"], name="app_core_re_last_ge_d3633f_idx"
            ),
        ),
    ]
