# Generated by Django 5.2.7 on 2025-11-17 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0014_budget_recurring_group_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name (e.g., 'Q4 Marketing Campaign', 'Client XYZ')",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Project description and notes",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Project budget",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("on-hold", "On Hold"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Labels to track in this project",
                        related_name="projects",
                        to="app_core.label",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Percentage of the transaction allocated to this project (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Allocation notes",
                        max_length=256,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_transactions",
                        to="app_core.project",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_allocations",
                        to="app_core.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "name"], name="app_core_pr_user_id_0e76a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "status"], name="app_core_pr_user_id_9f1a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["start_date"], name="app_core_pr_start_d_5a0a36_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="projecttransaction",
            index=models.Index(
                fields=["project", "transaction"], name="app_core_pr_project_5dba7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projecttransaction",
            unique_together={("project", "transaction")},
        ),
    ]
