# Generated by Django 5.2.7 on 2025-11-17 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0015_project_projecttransaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("budget_changed", "Budget Changed"),
                            ("milestone_added", "Milestone Added"),
                            ("milestone_completed", "Milestone Completed"),
                            ("sub_project_added", "Sub-Project Added"),
                            ("transaction_added", "Transaction Added"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the action"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Labor, Materials, Marketing)",
                        max_length=64,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budgeted amount for this category",
                        max_digits=12,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Milestone name (e.g., 'Design Phase Complete')",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Milestone details"
                    ),
                ),
                ("due_date", models.DateField(help_text="Milestone due date")),
                (
                    "completed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when milestone was completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget allocated to this milestone",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Person responsible for this milestone",
                        max_length=128,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "due_date"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="level",
            field=models.PositiveIntegerField(
                default=0, help_text="Hierarchy level: 0=parent, 1=sub-project, 2=task"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="parent_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent project if this is a sub-project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_projects",
                to="app_core.project",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["parent_project"], name="app_core_pr_parent__3b5e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["level"], name="app_core_pr_level_23a901_idx"),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="app_core.project",
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="projectbudgetcategory",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Labels that count toward this category",
                related_name="budget_categories",
                to="app_core.label",
            ),
        ),
        migrations.AddField(
            model_name="projectbudgetcategory",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_categories",
                to="app_core.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="app_core.project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectactivity",
            index=models.Index(
                fields=["project", "-created_at"], name="app_core_pr_project_b0baed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectbudgetcategory",
            index=models.Index(
                fields=["project"], name="app_core_pr_project_9b9ed6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectbudgetcategory",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["project", "order"], name="app_core_pr_project_5b8500_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["due_date"], name="app_core_pr_due_dat_b703c7_idx"
            ),
        ),
    ]
