# Generated by Django 5.2.7 on 2025-11-17 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0016_projectactivity_projectbudgetcategory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Client name", max_length=128)),
                (
                    "email",
                    models.EmailField(help_text="Client email address", max_length=254),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Company name (optional)",
                        max_length=128,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Phone number (optional)",
                        max_length=32,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", help_text="Full address"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="VAT/Tax ID (optional)",
                        max_length=64,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="Net 30",
                        help_text="Payment terms (e.g., Net 30, Net 60, Due on Receipt)",
                        max_length=64,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP",
                        help_text="Currency code (GBP, USD, EUR, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about the client",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether client is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice number (auto-generated)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("invoice_date", models.DateField(help_text="Invoice issue date")),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "sent_date",
                    models.DateField(
                        blank=True, help_text="Date invoice was sent", null=True
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="Date invoice was fully paid", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Subtotal before tax",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax rate percentage (e.g., 20 for 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax amount",
                        max_digits=12,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount",
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total invoice amount",
                        max_digits=12,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount paid so far",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes to client (visible on invoice)",
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True, default="", help_text="Payment terms and conditions"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes (not visible on invoice)",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this invoice recurs automatically",
                    ),
                ),
                (
                    "recurrence_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="How often the invoice recurs",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "recurrence_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of recurrences (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "recurring_group_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID linking related recurring invoices",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="app_core.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="app_core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Item/service description", max_length=256
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, help_text="Quantity", max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per unit", max_digits=12
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line total (quantity × unit_price)",
                        max_digits=12,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_core.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=12
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Date payment was received"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Payment reference/transaction ID",
                        max_length=128,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Payment notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="app_core.invoice",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the actual transaction (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_payments",
                        to="app_core.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=128)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Template description"
                    ),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default tax rate %",
                        max_digits=5,
                    ),
                ),
                (
                    "default_payment_terms",
                    models.CharField(
                        default="Net 30",
                        help_text="Default payment terms",
                        max_length=64,
                    ),
                ),
                (
                    "default_notes",
                    models.TextField(
                        blank=True, default="", help_text="Default notes for invoices"
                    ),
                ),
                (
                    "default_terms",
                    models.TextField(
                        blank=True, default="", help_text="Default terms and conditions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Item/service description", max_length=256
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Default quantity",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default price per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_core.invoicetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["user", "name"], name="app_core_cl_user_id_5edbca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["user", "email"], name="app_core_cl_user_id_6012e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["user", "active"], name="app_core_cl_user_id_13c022_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("user", "email")},
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="app_core_in_user_id_4159a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "invoice_date"], name="app_core_in_user_id_c0fe35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client"], name="app_core_in_client__9c4e8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="app_core_in_due_dat_49789a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="app_core_in_invoice_fffd12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["invoice", "order"], name="app_core_in_invoice_8544b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicepayment",
            index=models.Index(
                fields=["invoice", "payment_date"],
                name="app_core_in_invoice_c4de58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicetemplate",
            index=models.Index(
                fields=["user", "name"], name="app_core_in_user_id_e74106_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicetemplate",
            unique_together={("user", "name")},
        ),
    ]
