# Generated by Django 5.2.7 on 2025-11-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0017_client_invoice_invoiceitem_invoicepayment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name (e.g., 'Acme Corp')",
                        max_length=128,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", help_text="Default currency code", max_length=3
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.IntegerField(
                        default=4, help_text="Fiscal year start month (1-12)"
                    ),
                ),
                ("timezone", models.CharField(default="Europe/London", max_length=50)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=1, help_text="Maximum team members allowed"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Organization owner (cannot be deleted while org exists)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Workflow name (e.g., 'Large Expenses')",
                        max_length=128,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("budget", "Budget"),
                            ("expense_claim", "Expense Claim"),
                            ("invoice", "Invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum amount to trigger approval",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "approvals_required",
                    models.IntegerField(
                        default=1, help_text="Number of approvals needed"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Trigger only for specific labels/categories",
                        to="app_core.label",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflows",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=20)),
                (
                    "entity_id",
                    models.IntegerField(help_text="ID of the object being approved"),
                ),
                (
                    "entity_description",
                    models.CharField(
                        help_text="Human-readable description (e.g., 'Transaction: Office Supplies - £500')",
                        max_length=512,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approvals_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="app_core.approvalworkflow",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("export", "Exported"),
                            ("invite", "Invited"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("login", "Logged In"),
                            ("logout", "Logged Out"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transaction", "Transaction"),
                            ("budget", "Budget"),
                            ("project", "Project"),
                            ("invoice", "Invoice"),
                            ("member", "Team Member"),
                            ("role", "Role"),
                            ("label", "Label"),
                            ("approval", "Approval"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(
                        help_text="Human-readable description", max_length=512
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (old/new values, etc.)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., 'Accountant', 'Project Manager')",
                        max_length=64,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Role description"),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False, help_text="Organization owner role"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, help_text="System-created role"),
                ),
                (
                    "can_manage_organization",
                    models.BooleanField(
                        default=False, help_text="Change org settings, delete org"
                    ),
                ),
                (
                    "can_manage_members",
                    models.BooleanField(
                        default=False, help_text="Invite, remove members"
                    ),
                ),
                (
                    "can_manage_roles",
                    models.BooleanField(
                        default=False, help_text="Create, edit, delete roles"
                    ),
                ),
                ("can_view_transactions", models.BooleanField(default=True)),
                ("can_create_transactions", models.BooleanField(default=False)),
                ("can_edit_transactions", models.BooleanField(default=False)),
                ("can_delete_transactions", models.BooleanField(default=False)),
                ("can_export_transactions", models.BooleanField(default=False)),
                ("can_view_budgets", models.BooleanField(default=True)),
                ("can_create_budgets", models.BooleanField(default=False)),
                ("can_edit_budgets", models.BooleanField(default=False)),
                ("can_delete_budgets", models.BooleanField(default=False)),
                ("can_view_projects", models.BooleanField(default=True)),
                ("can_create_projects", models.BooleanField(default=False)),
                ("can_edit_projects", models.BooleanField(default=False)),
                ("can_delete_projects", models.BooleanField(default=False)),
                ("can_view_invoices", models.BooleanField(default=True)),
                ("can_create_invoices", models.BooleanField(default=False)),
                ("can_edit_invoices", models.BooleanField(default=False)),
                ("can_delete_invoices", models.BooleanField(default=False)),
                ("can_send_invoices", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=True)),
                ("can_export_reports", models.BooleanField(default=False)),
                ("can_approve_transactions", models.BooleanField(default=False)),
                ("can_approve_budgets", models.BooleanField(default=False)),
                ("can_approve_expenses", models.BooleanField(default=False)),
                ("can_approve_invoices", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="app_core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="app_core.organizationrole",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "user"],
            },
        ),
        migrations.AddField(
            model_name="approvalworkflow",
            name="approver_roles",
            field=models.ManyToManyField(
                related_name="approval_workflows", to="app_core.organizationrole"
            ),
        ),
        migrations.CreateModel(
            name="PermissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(help_text="Requested permissions as JSON object"),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When permissions should become active"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="When permissions should expire"),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why these permissions are needed"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to="app_core.organizationmember",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="app_core_or_slug_fbd807_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["owner"], name="app_core_or_owner_i_76d604_idx"),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="app_core_ap_organiz_aa5aee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="app_core_ap_entity__1b1170_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["requested_by", "status"], name="app_core_ap_request_8ac5b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["status", "-created_at"], name="app_core_ap_status_3e7afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="app_core_ac_organiz_0ea9fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="app_core_ac_entity__047293_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="app_core_ac_user_id_f8c3ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action", "-created_at"], name="app_core_ac_action_459d87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrole",
            index=models.Index(
                fields=["organization", "name"], name="app_core_or_organiz_86edb0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationrole",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "user"], name="app_core_or_organiz_f8cd4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["user", "is_active"], name="app_core_or_user_id_811df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "is_active"],
                name="app_core_or_organiz_cf1f13_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together={("organization", "user")},
        ),
        migrations.AddIndex(
            model_name="approvalworkflow",
            index=models.Index(
                fields=["organization", "is_active"],
                name="app_core_ap_organiz_641d81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionrequest",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="app_core_pe_organiz_439be7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionrequest",
            index=models.Index(
                fields=["member", "status"], name="app_core_pe_member__a70164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionrequest",
            index=models.Index(
                fields=["status", "end_date"], name="app_core_pe_status_28767d_idx"
            ),
        ),
    ]
