# Generated by Django 5.2.7 on 2025-11-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0018_add_team_collaboration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="app_core.organization",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="app_core.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="app_core.organization",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="app_core.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="app_core.organization",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="app_core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["organization", "active"], name="app_core_bu_organiz_6a9e83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["organization", "name"], name="app_core_cl_organiz_a5d675_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(
                fields=["organization", "name"], name="app_core_la_organiz_52cce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["organization", "date"], name="app_core_tr_organiz_ced770_idx"
            ),
        ),
    ]
