# Generated by Django 5.2.7 on 2025-11-20 13:29

from django.db import migrations
from django.utils.text import slugify


def create_personal_organizations(apps, schema_editor):
    """
    Create a personal organization for each existing user and link all their data.
    This migration ensures backward compatibility when introducing multi-tenancy.
    """
    # Get models
    User = apps.get_model('auth', 'User')
    Organization = apps.get_model('app_core', 'Organization')
    OrganizationRole = apps.get_model('app_core', 'OrganizationRole')
    OrganizationMember = apps.get_model('app_core', 'OrganizationMember')

    # Data models
    Label = apps.get_model('app_core', 'Label')
    Transaction = apps.get_model('app_core', 'Transaction')
    Budget = apps.get_model('app_core', 'Budget')
    Project = apps.get_model('app_core', 'Project')
    Client = apps.get_model('app_core', 'Client')
    Invoice = apps.get_model('app_core', 'Invoice')

    # Process each user
    for user in User.objects.all():
        # Create personal organization
        org_name = f"{user.username}'s Organization"
        base_slug = slugify(user.username)
        slug = base_slug
        counter = 1

        # Ensure unique slug
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        org = Organization.objects.create(
            name=org_name,
            slug=slug,
            owner=user,
            currency='GBP',
            fiscal_year_start=4,  # April
            timezone='Europe/London',
            plan='free',
            max_users=1,
            is_active=True
        )

        print(f"Created organization '{org_name}' for user {user.username}")

        # Create default roles
        owner_role = OrganizationRole.objects.create(
            organization=org,
            name='Owner',
            description='Organization owner with full access',
            is_owner=True,
            is_system=True,
            # Organization management
            can_manage_organization=True,
            can_manage_members=True,
            can_manage_roles=True,
            # Transactions
            can_view_transactions=True,
            can_create_transactions=True,
            can_edit_transactions=True,
            can_delete_transactions=True,
            can_export_transactions=True,
            # Budgets
            can_view_budgets=True,
            can_create_budgets=True,
            can_edit_budgets=True,
            can_delete_budgets=True,
            # Projects
            can_view_projects=True,
            can_create_projects=True,
            can_edit_projects=True,
            can_delete_projects=True,
            # Invoices
            can_view_invoices=True,
            can_create_invoices=True,
            can_edit_invoices=True,
            can_delete_invoices=True,
            can_send_invoices=True,
            # Reports
            can_view_reports=True,
            can_export_reports=True,
            # Approvals
            can_approve_transactions=True,
            can_approve_budgets=True,
            can_approve_expenses=True,
            can_approve_invoices=True,
        )

        admin_role = OrganizationRole.objects.create(
            organization=org,
            name='Admin',
            description='Administrator with most permissions',
            is_system=True,
            can_manage_members=True,
            can_manage_roles=True,
            can_view_transactions=True,
            can_create_transactions=True,
            can_edit_transactions=True,
            can_delete_transactions=True,
            can_export_transactions=True,
            can_view_budgets=True,
            can_create_budgets=True,
            can_edit_budgets=True,
            can_delete_budgets=True,
            can_view_projects=True,
            can_create_projects=True,
            can_edit_projects=True,
            can_delete_projects=True,
            can_view_invoices=True,
            can_create_invoices=True,
            can_edit_invoices=True,
            can_delete_invoices=True,
            can_send_invoices=True,
            can_view_reports=True,
            can_export_reports=True,
            can_approve_transactions=True,
            can_approve_budgets=True,
            can_approve_expenses=True,
        )

        viewer_role = OrganizationRole.objects.create(
            organization=org,
            name='Viewer',
            description='Read-only access to all data',
            is_system=True,
            can_view_transactions=True,
            can_view_budgets=True,
            can_view_projects=True,
            can_view_invoices=True,
            can_view_reports=True,
        )

        # Create organization membership for the user (as owner)
        OrganizationMember.objects.create(
            organization=org,
            user=user,
            role=owner_role,
            invited_by=user,
            accepted_at=org.created_at,
            is_active=True
        )

        # Link all existing data to the organization
        Label.objects.filter(user=user, organization__isnull=True).update(organization=org)
        Transaction.objects.filter(user=user, organization__isnull=True).update(organization=org)
        Budget.objects.filter(user=user, organization__isnull=True).update(organization=org)
        Project.objects.filter(user=user, organization__isnull=True).update(organization=org)
        Client.objects.filter(user=user, organization__isnull=True).update(organization=org)
        Invoice.objects.filter(user=user, organization__isnull=True).update(organization=org)

        # Count migrated records
        label_count = Label.objects.filter(organization=org).count()
        transaction_count = Transaction.objects.filter(organization=org).count()
        budget_count = Budget.objects.filter(organization=org).count()
        project_count = Project.objects.filter(organization=org).count()
        client_count = Client.objects.filter(organization=org).count()
        invoice_count = Invoice.objects.filter(organization=org).count()

        print(f"  Migrated {transaction_count} transactions, {budget_count} budgets, " +
              f"{project_count} projects, {client_count} clients, {invoice_count} invoices, " +
              f"{label_count} labels")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all organizations and their memberships.
    This is safe because the organization field in other models is nullable.
    """
    Organization = apps.get_model('app_core', 'Organization')
    Organization.objects.all().delete()  # This will cascade delete roles and members


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0019_add_organization_to_models"),
    ]

    operations = [
        migrations.RunPython(create_personal_organizations, reverse_migration),
    ]

