# Generated by Django 5.2.7 on 2025-11-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0020_populate_organizations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this budget",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this label",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this project (for audit trail)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed this action (null if deleted)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this recurring transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this rule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
