# Generated by Django 5.2.7 on 2025-12-03 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0023_dashboard_layout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "natural_language_input",
                    models.TextField(
                        help_text="User's original goal description in natural language"
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("runway", "Cash Runway"),
                            ("savings", "Savings Target"),
                            ("spending_limit", "Spending Limit"),
                            ("budget_compliance", "Budget Compliance"),
                            ("revenue_target", "Revenue Target"),
                            ("profit_margin", "Profit Margin"),
                        ],
                        help_text="Type of financial goal",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(help_text="Short goal name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="AI-generated description of the goal"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target value (amount, percentage, months, etc.)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="Date by which goal should be achieved",
                        null=True,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Type-specific parameters (categories, labels, formulas, etc.)",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("off_track", "Off Track"),
                            ("achieved", "Achieved"),
                            ("not_started", "Not Started"),
                        ],
                        default="not_started",
                        help_text="Current status of goal achievement",
                        max_length=16,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current progress value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Progress toward goal (0-100%)",
                        max_digits=5,
                    ),
                ),
                (
                    "last_explanation",
                    models.TextField(
                        blank=True, help_text="Latest AI explanation of goal status"
                    ),
                ),
                (
                    "last_recommendations",
                    models.JSONField(
                        default=list, help_text="List of AI-generated recommendations"
                    ),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of last evaluation", null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this goal is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this goal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this goal belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_goals",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Goal",
                "verbose_name_plural": "Financial Goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this evaluation was performed",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("off_track", "Off Track"),
                            ("achieved", "Achieved"),
                            ("not_started", "Not Started"),
                        ],
                        help_text="Goal status at time of evaluation",
                        max_length=16,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Goal value at time of evaluation",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Progress percentage at time of evaluation",
                        max_digits=5,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="KPIs and calculations at this point (inflow, outflow, net, etc.)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="AI-generated explanation of status"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="AI-generated recommendations [{action, impact, priority, reasoning}]",
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=list,
                        help_text="Identified risks [{risk, severity, mitigation}]",
                    ),
                ),
                (
                    "trend_analysis",
                    models.TextField(
                        blank=True,
                        help_text="AI trend commentary (patterns, acceleration, seasonality)",
                    ),
                ),
                (
                    "forecast",
                    models.JSONField(
                        default=dict,
                        help_text="Predicted outcomes {predicted_date, predicted_value, confidence, scenarios}",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        help_text="Goal this evaluation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="app_core.financialgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal Evaluation",
                "verbose_name_plural": "Goal Evaluations",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Auto-generated from first message", max_length=255
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("what_if", "What-If Simulation"),
                            ("goal_discussion", "Goal Discussion"),
                            ("general_insights", "General Insights"),
                        ],
                        default="what_if",
                        help_text="Type of conversation",
                        max_length=32,
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        default=list,
                        help_text="Conversation messages [{role, content, timestamp}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Goal this conversation is about (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="app_core.financialgoal",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_conversations",
                        to="app_core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playbook Conversation",
                "verbose_name_plural": "Playbook Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["organization", "active"], name="app_core_fi_organiz_06d51b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["goal_type", "current_status"],
                name="app_core_fi_goal_ty_fb3e16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["target_date"], name="app_core_fi_target__5fb174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goalevaluation",
            index=models.Index(
                fields=["goal", "evaluated_at"], name="app_core_go_goal_id_317954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goalevaluation",
            index=models.Index(
                fields=["evaluated_at"], name="app_core_go_evaluat_cf12b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playbookconversation",
            index=models.Index(
                fields=["organization", "user"], name="app_core_pl_organiz_13f02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playbookconversation",
            index=models.Index(fields=["goal"], name="app_core_pl_goal_id_736074_idx"),
        ),
        migrations.AddIndex(
            model_name="playbookconversation",
            index=models.Index(
                fields=["updated_at"], name="app_core_pl_updated_7d982a_idx"
            ),
        ),
    ]
