# Generated by Django 5.2.7 on 2025-11-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0023_dashboard_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("GBP", "British Pound (£)"),
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("INR", "Indian Rupee (₹)"),
                ],
                default="GBP",
                help_text="Organization's preferred currency for displaying amounts",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="display_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount converted to organization's preferred currency",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Exchange rate used for conversion",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_currency",
            field=models.CharField(
                default="GBP",
                help_text="Currency this transaction was originally in",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="rate_date",
            field=models.DateField(
                blank=True, help_text="Date when exchange rate was fetched", null=True
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_currency",
                    models.CharField(
                        help_text="Source currency code (e.g., 'USD')", max_length=3
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        help_text="Target currency code (e.g., 'GBP')", max_length=3
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, help_text="Exchange rate", max_digits=10
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date for this exchange rate"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="exchangerate-api.com",
                        help_text="API source for the rate",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "date"],
                        name="app_core_ex_from_cu_7482d9_idx",
                    ),
                    models.Index(fields=["date"], name="app_core_ex_date_2bba75_idx"),
                ],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
    ]
