# Generated by Django 5.2.7 on 2025-12-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0024_financialgoal_goalevaluation_playbookconversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="original_currency",
            field=models.CharField(
                default="GBP",
                help_text="Original currency code (ISO 4217)",
                max_length=3,
            ),
        ),
    ]
