# Generated by Django 5.2.7 on 2025-12-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_core", "0026_financialgoal_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date this score was calculated for"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall health score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("great", "Great"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("needs_improvement", "Needs Improvement"),
                        ],
                        help_text="Score level/category",
                        max_length=20,
                    ),
                ),
                (
                    "runway_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Runway component score (30% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "revenue_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue growth component score (25% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "expense_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense control component score (20% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "goal_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Goal progress component score (15% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "stability_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Financial stability component score (10% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="AI-generated explanation of the score"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this score belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="app_core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Score",
                "verbose_name_plural": "Health Scores",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date"],
                        name="app_core_he_organiz_527309_idx",
                    ),
                    models.Index(fields=["date"], name="app_core_he_date_0e5cdd_idx"),
                ],
                "unique_together": {("organization", "date")},
            },
        ),
    ]
