# app_core/playbook_models.py
"""
AI Financial Playbook Models
Goal tracking, evaluation history, and AI conversations for proactive financial intelligence.
"""

from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()


class FinancialGoal(models.Model):
    """
    User-defined financial goals created via natural language input.
    Organization-level, evaluated continuously by AI.
    """
    GOAL_TYPES = [
        ('runway', 'Cash Runway'),
        ('savings', 'Savings Target'),
        ('spending_limit', 'Spending Limit'),
        ('budget_compliance', 'Budget Compliance'),
        ('revenue_target', 'Revenue Target'),
        ('profit_margin', 'Profit Margin'),
    ]

    STATUS_CHOICES = [
        ('on_track', 'On Track'),
        ('at_risk', 'At Risk'),
        ('off_track', 'Off Track'),
        ('achieved', 'Achieved'),
        ('not_started', 'Not Started'),
    ]

    organization = models.ForeignKey(
        'Organization',
        on_delete=models.CASCADE,
        related_name='financial_goals',
        help_text="Organization this goal belongs to"
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_goals',
        help_text="User who created this goal"
    )

    # Natural language input
    natural_language_input = models.TextField(
        help_text="User's original goal description in natural language"
    )

    # Parsed/structured goal (generated by LLM, confirmed by user)
    goal_type = models.CharField(
        max_length=32,
        choices=GOAL_TYPES,
        help_text="Type of financial goal"
    )
    name = models.CharField(
        max_length=255,
        help_text="Short goal name"
    )
    description = models.TextField(
        blank=True,
        help_text="AI-generated description of the goal"
    )

    # Goal parameters (JSON for flexibility across different goal types)
    target_value = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Target value (amount, percentage, months, etc.)"
    )
    target_date = models.DateField(
        null=True,
        blank=True,
        help_text="Date by which goal should be achieved"
    )
    parameters = models.JSONField(
        default=dict,
        help_text="Type-specific parameters (categories, labels, formulas, etc.)"
    )

    # Current status
    current_status = models.CharField(
        max_length=16,
        choices=STATUS_CHOICES,
        default='not_started',
        help_text="Current status of goal achievement"
    )
    current_value = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Current progress value"
    )
    progress_percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0,
        help_text="Progress toward goal (0-100%)"
    )

    # AI-generated insights (cached, regenerated on evaluation)
    last_explanation = models.TextField(
        blank=True,
        help_text="Latest AI explanation of goal status"
    )
    last_recommendations = models.JSONField(
        default=list,
        help_text="List of AI-generated recommendations"
    )
    last_evaluated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp of last evaluation"
    )

    # Metadata
    active = models.BooleanField(
        default=True,
        help_text="Whether this goal is active"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['organization', 'active']),
            models.Index(fields=['goal_type', 'current_status']),
            models.Index(fields=['target_date']),
        ]
        verbose_name = "Financial Goal"
        verbose_name_plural = "Financial Goals"

    def __str__(self):
        return f"{self.name} ({self.get_goal_type_display()}) - {self.get_current_status_display()}"

    def is_overdue(self):
        """Check if goal is past its target date and not achieved"""
        if self.target_date and self.current_status != 'achieved':
            return timezone.now().date() > self.target_date
        return False

    def days_until_target(self):
        """Calculate days remaining until target date"""
        if self.target_date:
            delta = self.target_date - timezone.now().date()
            return delta.days
        return None


class GoalEvaluation(models.Model):
    """
    Snapshot of goal evaluation at a point in time.
    Used for trend analysis and historical tracking.
    """
    goal = models.ForeignKey(
        FinancialGoal,
        on_delete=models.CASCADE,
        related_name='evaluations',
        help_text="Goal this evaluation belongs to"
    )

    # Snapshot data
    evaluated_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When this evaluation was performed"
    )
    status = models.CharField(
        max_length=16,
        choices=FinancialGoal.STATUS_CHOICES,
        help_text="Goal status at time of evaluation"
    )
    current_value = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        help_text="Goal value at time of evaluation"
    )
    progress_percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        help_text="Progress percentage at time of evaluation"
    )

    # Metrics snapshot (JSON for flexibility)
    metrics = models.JSONField(
        default=dict,
        help_text="KPIs and calculations at this point (inflow, outflow, net, etc.)"
    )

    # AI analysis
    explanation = models.TextField(
        blank=True,
        help_text="AI-generated explanation of status"
    )
    recommendations = models.JSONField(
        default=list,
        help_text="AI-generated recommendations [{action, impact, priority, reasoning}]"
    )
    risk_factors = models.JSONField(
        default=list,
        help_text="Identified risks [{risk, severity, mitigation}]"
    )
    trend_analysis = models.TextField(
        blank=True,
        help_text="AI trend commentary (patterns, acceleration, seasonality)"
    )
    forecast = models.JSONField(
        default=dict,
        help_text="Predicted outcomes {predicted_date, predicted_value, confidence, scenarios}"
    )

    class Meta:
        ordering = ['-evaluated_at']
        indexes = [
            models.Index(fields=['goal', 'evaluated_at']),
            models.Index(fields=['evaluated_at']),
        ]
        verbose_name = "Goal Evaluation"
        verbose_name_plural = "Goal Evaluations"

    def __str__(self):
        return f"{self.goal.name} - {self.evaluated_at.strftime('%Y-%m-%d %H:%M')} - {self.get_status_display()}"


class PlaybookConversation(models.Model):
    """
    Stores AI conversations for what-if simulations and Q&A.
    Maintains context across multiple messages.
    """
    CONVERSATION_TYPES = [
        ('what_if', 'What-If Simulation'),
        ('goal_discussion', 'Goal Discussion'),
        ('general_insights', 'General Insights'),
    ]

    organization = models.ForeignKey(
        'Organization',
        on_delete=models.CASCADE,
        related_name='playbook_conversations',
        help_text="Organization this conversation belongs to"
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='playbook_conversations',
        help_text="User who initiated this conversation"
    )
    goal = models.ForeignKey(
        FinancialGoal,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='conversations',
        help_text="Goal this conversation is about (optional)"
    )

    # Conversation metadata
    title = models.CharField(
        max_length=255,
        help_text="Auto-generated from first message"
    )
    conversation_type = models.CharField(
        max_length=32,
        default='what_if',
        choices=CONVERSATION_TYPES,
        help_text="Type of conversation"
    )

    # Messages stored as JSON array
    # Format: [{role: 'user'|'assistant', content: str, timestamp: str}]
    messages = models.JSONField(
        default=list,
        help_text="Conversation messages [{role, content, timestamp}]"
    )

    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']
        indexes = [
            models.Index(fields=['organization', 'user']),
            models.Index(fields=['goal']),
            models.Index(fields=['updated_at']),
        ]
        verbose_name = "Playbook Conversation"
        verbose_name_plural = "Playbook Conversations"

    def __str__(self):
        return f"{self.title} - {self.user.username} ({self.get_conversation_type_display()})"

    def add_message(self, role, content):
        """Add a message to the conversation"""
        message = {
            'role': role,
            'content': content,
            'timestamp': timezone.now().isoformat()
        }
        self.messages.append(message)
        self.save()

    def get_message_count(self):
        """Get number of messages in conversation"""
        return len(self.messages)

